export const DASHBOARD_CONSTANTS = {
  RECENT_EVENTS_COUNT: 5,
  MAX_EVENTS_HISTORY: 1000,
  TIMELINE_HEIGHT: 350,
  HEATMAP_HEIGHT: 300,
  VOLUME_CHART_MIN_HEIGHT: 300,
  CHART_UPDATE_DEBOUNCE_MS: 100,
  TIME_RANGES: ['6h', '12h', '24h'] as const,
} as const;

